import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Physics-Books',
      slug: 'physics-book',
      category: 'Books',
      image: '/images/shirt1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'Books',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Physics Book',
    },
    {
      name: 'Math-Books',
      slug: 'math-book',
      category: 'Math',
      image: '/images/shirt2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 80,
      brand: 'books',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Math Book',
    },
    {
      name: 'Chemistry-Books',
      slug: 'chemistry-book',
      category: 'chemistry',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'boi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Chemistry Book',
    },
    {
      name: 'Islamic-Books ',
      slug: 'islam-boi',
      category: 'islamic',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'boi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular Islamic Book',
    },
    {
      name: 'Java-Books',
      slug: 'programming-book',
      category: 'book',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'boi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Programming Book',
    },
    {
      name: 'C-Books',
      slug: 'java-program',
      category: 'java',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'javaprograming',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Cprogramming Book',
    },
  ],
};
export default data;
